[package]
name = "sikhar-render"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
sikhar-core = { workspace = true }
sikhar-text = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
log = { workspace = true }

