[package]
name = "sikhar-layout"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
sikhar-core = { workspace = true }
taffy = { workspace = true }
glam = { workspace = true }
slotmap = { workspace = true }

