[package]
name = "spark-render"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
spark-core = { workspace = true }
spark-text = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
log = { workspace = true }

